name: databricks_project
version: 1.0.0
config-version: 2

# Where dbt will look for models
profile: databricks_project

model-paths: ["models"]
test-paths: ["tests"]
snapshot-paths: ["snapshots"]
seed-paths: ["seed"]
macro-paths: ["macros"]
analysis-paths: ["analysis"]
target-path: "target"
clean-targets: ["target", "dbt_modules"]


models:
 
vars:
  terraform_outputs_path: "./dbt/terraform_outputs.json"
